# Source: fluentbit-resource/templates/fluentbit/outputs.yaml
# Elasticsearch index  in taco-es
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fbcr-taco-taco-es-platform
  namespace: lma
  labels:
    fluentbit.fluent.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "seperate-kube-0.*"
  es:
    index: platform
    host: eck-elasticsearch-es-http
    port: 9200
    type: kubernates
    httpUser:
      valueFrom:
        secretKeyRef:
          name: fluentbit-es-user-taco-es
          key: username
    httpPassword:
      valueFrom:
        secretKeyRef:
          name: fluentbit-es-user-taco-es
          key: password
    tls:
      verify: false


# outputs for loki---
# Loki taco-loki
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fbcr-taco-loki-taco-loki-syslog
  namespace: lma
  labels:
    fluentbit.fluent.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "syslog.*"
  loki:
    autoKubernetesLabels: "on"
    host: loki-loki-distributed-gateway
    port: 80
    labels:
    - job=syslog
    - $host
    - $ident
